#ifndef SIM_VERILATOR_SELFTEST_ADDRESS_MAP_H_
#define SIM_VERILATOR_SELFTEST_ADDRESS_MAP_H_

#define CL1_HAS_DEFAULT_UART 1
#define CL1_DEFAULT_UART_ADDR 0x10000000u
#define CL1_HAS_DEFAULT_HOST_EXIT 1
#define CL1_DEFAULT_HOST_EXIT_ADDR 0x10000004u

#endif
